### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by sumitguptaravi** [maanavshah/stock-market-india#1]
Hi , 

I have a small request for you, can you please tell me the steps for run this project? It will be very big help for me to learn.

Thank You.

**Comment by maanavshah** [comment]
Let's get step by step here.

**Identify the location for your application.**

Firs identify the location where for your application. Let's take it as /home/user/your_app. The path doesn’t matter, so feel free to locate the directory wherever it is best for you.

**Installing Node.js**

Here is where we will set up Node.js and Express. Node.js is a framework and Express provides a web server. The webserver we need does not need to do anything fancy. The only feature that the webserver needs are the ability to provide static files.

To get started download and install Node.JS: [nodejs.org](http://nodejs.org/)

**Install Express**

Express is a package that executes within Node.js. To install express, in the Command Prompt navigate to your directory for the application which is  /home/user/your_app.

Now let's install Express as a package for Node.js. At the command prompt type “npm install express”. That installed Express and should have created a directory called “node_modules”. 

**Start Express Web Server in Node.js**

In the terminal confirm you are at the  /home/user/your_app directory and execute the following command.

> node app.js 3000

Now the webserver should be running on port 3000 and you should be able to access the APIs.

**Comment by javiyacollection** [comment]
Hi, Maanav shah,

I tried the same steps as you mentioned.

But I am getting below errors, can you please help??
-------------------------------------------------------------------------------------

C:\Software\stock-market-india-master>npm install express
+ express@4.17.1
added 61 packages from 44 contributors and audited 139 packages in 7.301s
found 3 vulnerabilities (2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Software\stock-market-india-master>node app.js 3000
Server running on port 3000
(node:13816) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at transformResponse (C:\Software\stock-market-india-master\nse\service\API.js:91:22)
    at transform (C:\Software\stock-market-india-master\node_modules\axios\lib\core\transformData.js:16:12)
    at Object.forEach (C:\Software\stock-market-india-master\node_modules\axios\lib\utils.js:218:10)
    at transformData (C:\Software\stock-market-india-master\node_modules\axios\lib\core\transformData.js:15:9)
    at onAdapterResolution (C:\Software\stock-market-india-master\node_modules\axios\lib\core\dispatchRequest.js:63:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------------------------------------------
when I tried to access http://localhost:3000/get_market_status. --> It keeps loading. It doesn't give any response.

can you please let me know, what wrong I am doing?? Thanks in advance.

**Comment by maanavshah** [comment]
Hi,

Did this resolve the setup of this project?

PS., if it helps, please close the issue.

**Comment by sachinbanugariya** [comment]
node app.js 3000
/opt/stock-market-india/bse/service/API.js:92
      ...response,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/stock-market-india/bse/index.js:1:73)


getting above issue while run app.

**Comment by Nahdus** [comment]
you could try deleting the node_modules folder and package-lock-json and try running `npm install` again. 
and then run 
`node app.js 3000`
